### ISSUE TITLE
Feature request: Convenience overloads for ILogger

### ISSUE THREAD

**Issue by rofr** [patriksvensson/blackbox#8]
How about 

```
logger.Warn(...);
```

as an alternative to

```
logger.Write(LogLevel.Warning, ...);
```

and so on for each possible LogLevel

**Comment by patriksvensson** [comment]
Personally, I want to keep the number of overloads in the core library to as few as possible, but I think it would be nice to have an assembly with extension methods that does this. What do you think?

Maybe BlackBox.Convenience would be a good assembly name?

**Comment by rofr** [comment]
Implementing as extension methods sounds good. But do you really need a separate assembly? It will keep the assembly byte count down but add a bit of deployment and distribution pain. A separate namespace would be sufficient to hide the extensions.

**Comment by patriksvensson** [comment]
I understand your issue with multiple assemblies and I somewhat agree, even though you can use ILMerge to make one nice assembly out of BlackBox.

Personally I don't like extension methods in a different namespace than the target type, since it's confusing if you forget to include it, so I think the best way of doing this would be to have the extension methods in the same assembly and namespace as everything else.

**Comment by rofr** [comment]
Good points there... I've seen many developers puzzled by missing IEnumerable<T> extensions because they didn't have a using System.Linq. Another aspect is you can access internals if they are included in the core assembly.

Of course, blackbox users have the option of writing their own extension methods adapting it to the needs of a specific project. I'll share my extensions and you can decide if they are common enough to include in the distribution.
